version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: 'yarn start'
    links:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: isylzjkoot
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
       PMA_HOST: mysql
       PMA_PORT: 3306
    ports:
      - "8080:80"